### PR TITLE
Added Google Analytics

### LINKED ISSUE #17: Add Google Analytic to React
add google analytics to react

tracking id
```
UA-101263186-4
```

### PR DESCRIPTION
**Pull request by mdew192837**
Fixes #17 

Not sure if this is right. Please check and give me some advice.

### CODE REVIEW

**Comment by bossbossk20** [comment]
@mdew192837 no react-router in this project.

[https://github.com/react-ga/react-ga](https://github.com/react-ga/react-ga)

**Comment by mdew192837** [comment]
React router is needed to use react-ga using npm according to the readme. Let me know if that is correct.

**Comment by mdew192837** [comment]
Also, is your Travis CI working? @bossbossk20

**Comment by mdew192837** [comment]
Also, I run app by using npm run right? How do I test to make sure the Analytics is working, or is that only on your end?

**Comment by bossbossk20** [comment]
@mdew192837 You can use GA without react-router.

**Pull request merged**
