### PR TITLE
Added a green "Fork me" Github Ribbon to the app.

### LINKED ISSUE #16: add github ribbon
add GitHub Ribbon on the left corner 

[example](https://github.com/blog/273-github-ribbons)

### PR DESCRIPTION
**Pull request by TheCodeArtist**
Fixes #16

### CODE REVIEW

**Comment by bossbossk20** [comment]
@TheCodeArtist Expected corresponding JSX closing tag for  can you fix it.

**Comment by TheCodeArtist** [comment]
Searching online, apparently an alternate approach could be as follows:

```
(function(){
	var mlink=document.createElement('a');
	mlink.setAttribute("href","https://github.com/bossbossk20/youtube-player-socket.io/");
	mlink.setAttribute("style","    position: absolute; top: 0; right: 0; z-index: 1000;");
	mlink.innerHTML='<img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/121cd7cbdc3e4855075ea8b558508b91ac463ac2/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png">';
	document.body.insertBefore(mlink, document.body.childNodes[0]);
})();
```

But being new to javascript, am not sure how to call the above `function()`
Any suggestions on how to use the above code-snippet?

**Comment by bossbossk20** [comment]
@TheCodeArtist Ribbon is an image you don't have to create any function.

just use img tag 

```
<img  src='url'  />
```

and create style
position: absolute 
top: 0
left: 0
border: 0

**Comment by TheCodeArtist** [comment]
Waiting for an `npm install` to complete...

I shall then run `npm start` and test out my latest change in `app.js` before updating the commit properly.

**Comment by bossbossk20** [comment]
@TheCodeArtist  Congratulations you did it.

**Comment by TheCodeArtist** [comment]
Thank You @bossbossk20 ! My FIRST JS contribution!

**Comment by bossbossk20** [comment]
it's very cool man. @TheCodeArtist

**Pull request merged**
