### PR TITLE
added github ribbon

### PR DESCRIPTION
**Pull request by ab-anand**
added green github ribbon at the top left corner with the href to this repository
ribbon

### CODE REVIEW

**Comment by bossbossk20** [comment]
@ab-anand You must do it in React please :yum:

**Comment by ab-anand** [comment]
With my beginner knowledge of React, I've tried it. Please check if it is correct or not.

**Comment by bossbossk20** [comment]
@ab-anand it not correct, I must not do anything with  HTML file. You just add a ribbon to src/App.js

first time you have to 

```shell
$ npm install
```
and run by command 

```shell
$ npm start
```

**Comment by TheCodeArtist** [comment]
FYI, superceded by https://github.com/bossbossk20/youtube-player-socket.io/pull/18

**Comment by mdew192837** [comment]
Should close this now.

**Pull request closed without merging**
