### PR TITLE
Change yarn install to yarn add

### PR DESCRIPTION
**Pull request by gabrielpaivadev**

### CODE REVIEW

**Comment by bossbossk20** [comment]
It must be 
```
  yarn install
  yarn build 
  yarn global add  firebase-tools
```

Can you fix it again @gpgabrielpaiva

**Comment by gpgabrielpaiva** [comment]
Fixed

**Comment by bossbossk20** [comment]
yarn install is missing @gpgabrielpaiva

**Comment by bossbossk20** [comment]
@gpgabrielpaiva  yarn global add firebase-tools  // should no -g

**Comment by gabrielpaivadev** [comment]
I'm sorry, fix!

**Comment by bossbossk20** [comment]
@gpgabrielpaiva you did it 👍

**Pull request merged**
